# Numpy

Arrays
1. Faster
2. Contigous memory allocation
3. Same data type
4. If you want to increase the size, you must have to recreate array

List
1. Slow
2. Sparse memory
3. Can store diferent data types
4. Can dynamically grow

## Comparison of Numpy with Python!

In [1]:
import numpy as np

In [2]:
python_list = range(1000000)

In [3]:
numpy_list = np.arange(1000000)

#### Multiplying a list with 6, and making a loop of 100

In [4]:
%time for i in range(100): result = [i*6 for i in python_list]

CPU times: total: 10 s
Wall time: 10.1 s


#### Multiplying an array with 6, and making a loop of 100

In [5]:
%time for i in range(100): result = numpy_list*6

CPU times: total: 188 ms
Wall time: 188 ms


## Numpy Array Creation

 #### For one dimensional arrays

In [6]:
one_d_array = np.zeros((10))

In [7]:
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### For two dimensional arrays

In [8]:
two_d_array = np.ones((10,10))

In [9]:
two_d_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

The built-in value for making array is 0,1, but it can understand all digits, like:

#### Can multiply divide add substarct to make new values

In [10]:
a = np.ones(10) * 5

In [11]:
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Same applies here!

In [12]:
b = np.zeros(5)+10

In [13]:
b

array([10., 10., 10., 10., 10.])

#### Making array by range

In [14]:
c = np.arange(1,16)

In [15]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Multi diumentional arrays!

#### Two dimensional array

In [16]:
i = np.zeros((5,6))
i

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Three dimensional array
* The first number '5' is depth of array '6' is coulmn and '7' is row!

In [17]:
o = np.zeros((5,6,7))
o

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
    

#### 'n' Dimensional array
* Can make n numbers of dimention in arrays.
* Normally three dimensional array is enough!

In [18]:
p = np.zeros((5,6,7,8))
p

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 

#### To check the shape

In [19]:
p.shape

(5, 6, 7, 8)

## Custom elements arrays

In [20]:
x = np.array([45,32,46,84,31,6,56,21])
x

array([45, 32, 46, 84, 31,  6, 56, 21])

In [21]:
x.shape

(8,)

## Reshaping an array

* the first number is always Row and the second number is Coloumn!

In [22]:
y = x.reshape(4,2)
y

array([[45, 32],
       [46, 84],
       [31,  6],
       [56, 21]])

In [23]:
y.shape

(4, 2)

#### To check the numbers of dimension

In [24]:
y.ndim

2

## for accessing indivisual elements

In [25]:
y[2,1]

6

In [26]:
y[3,0]

56

In [27]:
y = x.reshape(2,2,2)
y

array([[[45, 32],
        [46, 84]],

       [[31,  6],
        [56, 21]]])

In [28]:
y[1,0,0]

31

## Slicing
Slicing dependes on three things:
1. Start
2. End
3. Step

In [29]:
y = y.reshape(4,2)

In [30]:
y

array([[45, 32],
       [46, 84],
       [31,  6],
       [56, 21]])

In [31]:
y[1:3]

array([[46, 84],
       [31,  6]])

#### Mixing indexing and slicing

* "1:4" is representing the slicing and "0" is coloumn

In [32]:
y[1:4,0]

array([46, 31, 56])

In [33]:
y

array([[45, 32],
       [46, 84],
       [31,  6],
       [56, 21]])

* " :: " Representing all components of array and "2" is representing the step size.

In [34]:
y[::2]

array([[45, 32],
       [31,  6]])

In [35]:
y

array([[45, 32],
       [46, 84],
       [31,  6],
       [56, 21]])

In [36]:
y[::,0]

array([45, 46, 31, 56])

In [37]:
y[::,1]

array([32, 84,  6, 21])

In [38]:
y[2,::]

array([31,  6])

In [39]:
y[::2,0]

array([45, 31])

#### For Fancy Indexing

In [40]:
x

array([45, 32, 46, 84, 31,  6, 56, 21])

* Have to pass double list (double square bracket)

In [41]:
x[[2,7]]

array([46, 21])

## Vectorizing operations

In [42]:
num1 = np.array([73,64,34])
num1

array([73, 64, 34])

In [43]:
num2 = np.array([44,88,55])
num2

array([44, 88, 55])

In [44]:
num1 + num2

array([117, 152,  89])

In [45]:
num1 - num2

array([ 29, -24, -21])

In [46]:
num3 = np.array([24,31,11])
num3

array([24, 31, 11])

In [47]:
(num1/num3)*num2

array([133.83333333, 181.67741935, 170.        ])

In [48]:
4/num2

array([0.09090909, 0.04545455, 0.07272727])

In [49]:
8*num1

array([584, 512, 272])

In [50]:
num1*num3**2

array([42048, 61504,  4114])

## Practicing shapes

In [51]:
t = np.zeros((5,5))
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
t[0] = 1

In [53]:
t[4] = 1

In [54]:
t

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [55]:
t[::,0] = 1

In [56]:
t[::,4] = 1

In [57]:
t

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Garbage Generation or Arbitrary genration or  (kinda) random generation

* The value shown which is shown in the below "np.empty" is already generated above, so it is just printing the already generated code.

In [58]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.empty((5,9))

array([[ 2.12199579e-314,  4.94065646e-324,  1.18831764e-312,
         0.00000000e+000,  1.39067116e-309,  8.69169479e-311,
         2.13684976e-311,  1.69760311e-313,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  1.55367112e+030, -3.72620332e-212,
         1.00158201e-311,  4.94065646e-324,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         5.01402526e+180,  1.30480151e-037,  7.40891732e+006,
         7.12593715e+059,  9.41170396e+218,  1.05193219e+189],
       [ 1.81531938e-306,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  4.94065646e-324]])

In [60]:
np.empty((7,5))

array([[1.00304139e-311, 1.00299541e-311, 0.00000000e+000,
        0.00000000e+000, 6.96320081e-077],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 7.06652016e-096],
       [7.06652016e-096, 7.18988929e+140, 6.01347002e-154,
        6.98345625e-077, 6.98345624e-077],
       [6.98345624e-077, 6.01391519e-154, 7.06673073e-096,
        7.06652016e-096, 7.06652016e-096],
       [1.81148490e-152, 9.37041222e-076, 6.98345624e-077,
        6.98345624e-077, 1.03080217e+136],
       [6.01347002e-154, 7.06652016e-096, 7.06652016e-096,
        7.18988929e+140, 4.99874708e+217],
       [4.47303447e-143, 1.46899974e+179, 9.08367237e+223,
        1.16466228e-028, 7.07980761e-308]])

In [61]:
np.empty((2,2))

array([[1.00299939e-311, 4.67296746e-307],
       [1.69121096e-306, 0.00000000e+000]])

## To check data type

In [62]:
x.dtype

dtype('int32')

In [63]:
num3.dtype

dtype('int32')

## Storing variables in Array

* Can store any data type but it should be one at a time!

e.g: 
  In an array of numbers you can not add any integers and vice versa.

In [64]:
name = np.array(('Hassan','Subhan','Arsalan','Faizan','Rayyan','Affan'))

In [65]:
name

array(['Hassan', 'Subhan', 'Arsalan', 'Faizan', 'Rayyan', 'Affan'],
      dtype='<U7')

In [66]:
name.reshape(2,3)

array([['Hassan', 'Subhan', 'Arsalan'],
       ['Faizan', 'Rayyan', 'Affan']], dtype='<U7')

## Comparison

* For True and False conditions

In [67]:
salary = np.array([37000,450000,98000,5000,60000])

In [68]:
salary >  45000

array([False,  True,  True, False,  True])

In [69]:
salary < 30000

array([False, False, False,  True, False])

* To print the Value

In [70]:
salary [salary >= 60000]

array([450000,  98000,  60000])

## Numpy Eliment-Wise Functions

In [71]:
val = np.array([46,24,76,35,46])

* We can apply any "Trignometric, Algebric ,etc Functions" to every single element present in the array

In [72]:
np.cos(val)

array([-0.43217794,  0.42417901,  0.82433133, -0.90369221, -0.43217794])

In [73]:
np.tan(val)

array([-2.08661353, -2.1348967 ,  0.68674769,  0.47381472, -2.08661353])

In [74]:
np.sin(val)

array([ 0.90178835, -0.90557836,  0.56610764, -0.42818267,  0.90178835])

In [75]:
np.sqrt(val)

array([6.78232998, 4.89897949, 8.71779789, 5.91607978, 6.78232998])

## Where Function
#### It is just like "If and Else" function of "Vanilla Python"

In [76]:
marks = np.array([22,64,35,89,91,44,30])

* The first condition "Pass" will only be execute if the condition is true, similarly the second condion "Fail" will be executeif the condition is false!

In [77]:
np.where(marks >= 40, "Pass", "Fail")

array(['Fail', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail'],
      dtype='<U4')

In [78]:
salary = np.array([30,35,40,45,50,55,60])

In [79]:
np.where(salary < 45, salary*1.1, salary*1.05)

array([33.  , 38.5 , 44.  , 47.25, 52.5 , 57.75, 63.  ])

## Transpose
#### Row became column and column became row
1. Can use it by " .T "
2. Can also use it by "transpose()"

In [80]:
matrix = np.arange(1,101).reshape(10,10)

In [81]:
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [82]:
matrix.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [83]:
matrix.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Mean Function

* It is sue to calculate mean of the elements in array

In [84]:
arr = np.array([5,6,4,8,2,3,7])

In [85]:
arr.mean()

5.0

In [86]:
matrix.mean()

50.5

## Cumsum Function

* In this function all the elements in array will make sum with each other in sequence, means 1st num will add with 2nd num, 2nd num will then bw added in 3rd num etc.

In [87]:
arr.cumsum()

array([ 5, 11, 15, 23, 25, 28, 35], dtype=int32)

## Cumprod Function

* It is same as "cumsum", the difference is that it will multiply instead of adding

In [88]:
arr.cumprod()

array([    5,    30,   120,   960,  1920,  5760, 40320], dtype=int32)

## Method for "Boolean Array"
* Remember that methods always have "()" in there end!

In [89]:
gender = np.array(['Male','Female','Male','Male','Female','Male'])

In [90]:
gender[gender == 'Male']

array(['Male', 'Male', 'Male', 'Male'], dtype='<U6')

In [91]:
gender == 'Male'

array([ True, False,  True,  True, False,  True])

In [92]:
gender == 'Female'

array([False,  True, False, False,  True, False])

* The value of True is "1" and the value of False is "2"

Which Means if we want to count the number of "Trues" we just have to add it

In [93]:
a = gender == 'Male'

In [94]:
a.sum()

4

In [95]:
b = gender == 'Female'

In [96]:
b.sum()

2

#### To check that is there any value true

In [97]:
a

array([ True, False,  True,  True, False,  True])

* any() is an existential quantifier!

In [98]:
a.any()

True

#### To check if all the conditions are true

In [99]:
a.all()

False

* This "False" doesn't means that all the element in the array is false, instead it is telling that all of them are not true, weather only one element is false or whole array ia false it will always give the answer false until, the whole array is true

In [100]:
b.all()

False

In [101]:
 n = np.array([22,34,18,6,98])

* It is telling that if all the elements are even numbers (divisible by "2") then the condition is true

In [102]:
x = n%2 == 0

* all() is a universal quantifier

In [103]:
x.all()

True

#### To arrange or sort array

In [104]:
n

array([22, 34, 18,  6, 98])

In [105]:
n.sort()

In [106]:
n

array([ 6, 18, 22, 34, 98])

* Can also change its order by

In [107]:
n[::-1]

array([98, 34, 22, 18,  6])

#### For unique conditions

* If there is any an element multiple times in a  singular array "np.unique()" is use to print the array in such way that all the element will print one time only!

In [108]:
num = np.array([2,3,4,3,5,6,2,6,7,5])
num

array([2, 3, 4, 3, 5, 6, 2, 6, 7, 5])

In [109]:
np.unique(num)

array([2, 3, 4, 5, 6, 7])

## Saving an array

In [110]:
u = np.unique(num)

* 'Data' is a the file name (it can be anything) and "u" is the array name 

In [111]:
np.save('Data',a)

## Loading the saved array

In [112]:
load_array = np.load('Data.npy')

In [113]:
load_array

array([ True, False,  True,  True, False,  True])

## Saving multiple arrays in asingle file

In [114]:
students = np.array(['Hashim', 'Ikram', 'Ali', 'Nizam'])
marks = np.array([60,70,77,80])

In [115]:
age = np.array([18,18,20,18])

* 'arrays' is a the file name (it can be anything) and the arrays which we are goingto save will always have to be in keyword arguments (and also it can be anything). We can store n numbers of arrays using the following method

In [116]:
np.savez('arrayz',a1=students,a2=marks,a3=age)

## Loading the saved arrays

* The load result of saving multiple array will be in the form of dictionary

In [117]:
result = np.load('arrayz.npz')

In [118]:
result['a1']

array(['Hashim', 'Ikram', 'Ali', 'Nizam'], dtype='<U6')

In [119]:
result['a2']

array([60, 70, 77, 80])

In [120]:
result['a3']

array([18, 18, 20, 18])

## Linear Algebra Functions

In [121]:
arr = np.arange(16).reshape(4,4)

In [122]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Different Linear Algebraic Functions

* To get diagnal elements out of matrices

In [123]:
arr.diagonal()

array([ 0,  5, 10, 15])

* trace() is the sum of diagonal elements of matrices

In [124]:
arr.trace()

30

* dot() is use to multiply a a number or a matrix to another matrix

In [125]:
arr.dot(5)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [126]:
arr1 = np.arange(40,56).reshape(4,4)

In [127]:
arr1

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55]])

In [128]:
arr.dot(arr1)

array([[ 296,  302,  308,  314],
       [1032, 1054, 1076, 1098],
       [1768, 1806, 1844, 1882],
       [2504, 2558, 2612, 2666]])

#### Some of these Functions requires a specific library of "Numpy"

There are two different methods to import
1. import numpy.linalg as lg
2. from numpy import linalg as lg

In [129]:
from numpy import linalg as lg

In [130]:
lg.det(arr)

0.0

In [131]:
lg.det(arr1)

2.0115953083135402e-28

* For eigenvalues

In [132]:
lg.eig(arr1)

(array([ 1.90420124e+02+0.00000000e+00j, -4.20123664e-01+0.00000000e+00j,
        -1.45875422e-15+7.13162765e-15j, -1.45875422e-15-7.13162765e-15j]),
 array([[-0.4350659 +0.j        ,  0.68237504+0.j        ,
         -0.13384489+0.27734221j, -0.13384489-0.27734221j],
        [-0.4768941 +0.j        ,  0.23528473+0.j        ,
         -0.15597242-0.41601331j, -0.15597242+0.41601331j],
        [-0.5187223 +0.j        , -0.21180558+0.j        ,
          0.71347952+0.j        ,  0.71347952-0.j        ],
        [-0.5605505 +0.j        , -0.65889589+0.j        ,
         -0.42366221+0.1386711j , -0.42366221-0.1386711j ]]))

* For Inverse

In [133]:
lg.inv(arr1)

array([[-2.82578800e+14,  4.22212465e+14,  3.31147031e+12,
        -1.42945135e+14],
       [ 4.23868200e+14, -5.62949953e+14, -1.45704694e+14,
         2.84786447e+14],
       [ 0.00000000e+00, -1.40737488e+14,  2.81474977e+14,
        -1.40737488e+14],
       [-1.41289400e+14,  2.81474977e+14, -1.39081753e+14,
        -1.10382344e+12]])

* For qr

qr decompose a single matrix into two matrices

In [134]:
lg.qr(arr1)

(array([[-0.43274232, -0.71605452,  0.21170681, -0.50515366],
        [-0.47601655, -0.27093955,  0.09424356,  0.83133516],
        [-0.51929079,  0.17417542, -0.82360756, -0.14720933],
        [-0.56256502,  0.6192904 ,  0.51765719, -0.17897217]]),
 array([[-9.24337601e+01, -9.44243747e+01, -9.64149894e+01,
         -9.84056041e+01],
        [ 0.00000000e+00, -1.93528250e-01, -3.87056500e-01,
         -5.80584750e-01],
        [ 0.00000000e+00,  0.00000000e+00, -9.50850281e-15,
         -1.59654957e-14],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          7.91655513e-15]]))

* Singular value decomposition

In [135]:
lg.svd(arr1)

(array([[-0.43495535, -0.71471242,  0.21784798, -0.50253583],
        [-0.47685242, -0.26946571,  0.08410412,  0.83242207],
        [-0.51874949,  0.175781  , -0.82175217, -0.15723665],
        [-0.56064657,  0.62102772,  0.51980008, -0.17264959]]),
 array([1.90892180e+02, 4.19084742e-01, 4.22271458e-15, 7.22000242e-18]),
 array([[-0.48421741, -0.49464845, -0.50507949, -0.51551053],
        [ 0.68230015,  0.23520822, -0.21188371, -0.65897564],
        [-0.22222205,  0.66943393, -0.67220172,  0.22498983],
        [ 0.50061698, -0.50185477, -0.4981414 ,  0.49937919]]))

## For Random Numbers Generation
* We have to import "random library"

In [136]:
from numpy import random as r

#### Normal Distribution
* "3,4" are normal distribution and "3,3" is size of matrices
* Normally we generate code using "Normal Distributions"

In [137]:
r.normal(3,4,(3,3))

array([[-1.31175329,  0.44052761,  5.80641395],
       [ 0.28866088,  2.57705289, -5.71319908],
       [ 4.52354249,  1.65656437,  9.03371376]])

#### Gamma Distribution

In [138]:
r.gamma(4,4,(4,4))

array([[17.53270007,  6.79383579, 17.35428918,  4.98116301],
       [27.85218608, 13.78007581, 20.52823496, 15.58715682],
       [14.98565928, 18.95683009,  8.77466624, 10.19549978],
       [12.92426828,  7.33726631,  9.04967235,  7.85940634]])

#### Uniform Distribution

In [139]:
r.uniform(3,3,(5,5))

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

## Seed
##### Seed is very important in random number generation in "AI Machine Learning"
* If a person is working on a seed which is for example set on "5"(can be any digit) and generating random codes, since the code is random it is nearly imposible for me to get random codes as same as him, until I set my seed also on "5" in this way we all get same results of random generation if we are all using the same seed!

* For example:
1. If I generate random code not using a set seed the generation will be different all the time

In [140]:
r.rand()

0.8631091589020353

In [141]:
r.rand()

0.009739830715226216

In [142]:
r.rand()

0.7293446785813449

2. But if I use a set seed i will get the same result all the time

In [143]:
r.seed(5)

In [144]:
r.rand()

0.22199317108973948

## Reshaping In Detail

In [145]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

* "C" is for (row major) and "F" is Fortran which is for(column major).
* The default value is row major(C)

In [146]:
b = a.reshape((4,4),order='F')
b

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [147]:
c = a.reshape((4,4),order='C')
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Flattening an Array
* It is used to flatten a multi-dimentional array into a single dimentional form, there are two methods of flattening an array,
1. flatten()
2. ravel()
* Both commands almost does a same job with some differences

In [148]:
arr = np.array([[5,7,3],[8,4,1],[9,6,2]])

In [149]:
arr

array([[5, 7, 3],
       [8, 4, 1],
       [9, 6, 2]])

In [150]:
arr.flatten()

array([5, 7, 3, 8, 4, 1, 9, 6, 2])

* Can also do it by "reshape()" method

In [151]:
arr.reshape(9)

array([5, 7, 3, 8, 4, 1, 9, 6, 2])

## Concatenate or Stacking

In [152]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [153]:
b = np.array([[9,10,11,12],[13,14,15,16]])

In [154]:
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [155]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

* The default concatenation will always be row wise, but can be change into column wise by changing the value of axis
1. "0" is for row wise
2. "1" is for column wise

In [156]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

* Concatenation can also be done by,
1. "hstack()" which is horizontal(column) wise stacking
2. "vstack()" which is verticle(row) wise stacking

In [157]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [158]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

* Concatenation can also be done by,
1. "c_[]" which is horizontal(row) wise stacking
2. "r_[]" which is verticle(column) wise stacking
* Remember these ones are using square brackets []

In [159]:
np.c_[a,b]

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [160]:
np.r_[b,a]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [161]:
np.r_[b,a,b,b]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Spliting

#### Splitting One dimensional array

In [162]:
x = np.array([1,2,3,4,7,8,9])

* Here "x" is Array and "3" is the index

In [163]:
np.split(x,[3])

[array([1, 2, 3]), array([4, 7, 8, 9])]

In [164]:
np.split(x,[2,5])

[array([1, 2]), array([3, 4, 7]), array([8, 9])]

* First "2,7" in the range and the lasts 2"" is the inteval

In [165]:
l = np.arange(2,7,2)

In [166]:
np.split(x,l)

[array([1, 2]), array([3, 4]), array([7, 8]), array([9])]

#### Splitting Two dimensional array

In [167]:
q = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [168]:
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
np.split(q,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

* By default the split will alway be row wise, for column wise splitting we have to mention the axis!
1. "axis = 0" for row wise splitting
2. "axis = 1" for column wise splitting

In [170]:
np.split(q,[2],axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [171]:
np.split(q,[2],axis=1)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

* We can also use,
1. "vsplit" for verticle split.
2. "hsplit" for horizontal split.

In [172]:
np.hsplit(q,[2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [173]:
np.vsplit(q,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]